version: '3.7'
services:
  employees_db:
    image: genschsa/mysql-employees:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: college
#      MYSQL_DATABASE: cabin
#      MYSQL_USER: cabin
#      MYSQL_PASSWORD: cabinpw
