version: '3.7'
services:
  mysql-server:
    image: genschsa/mysql-employees:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: college
  eureka-server:
    build: eureka-server
    ports:
      - 8761:8761
    expose:
      - 8761
  spring-data-college:
    build: spring-data-college
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - MYSQL_HOST=mysql-server
      - EUREKA_HOST=eureka-server
    depends_on:
      - mysql-server
      - eureka-server
